version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      DB_HOST: 192.168.100.109
      DB_PORT: 15432
      DB_NAME: plataformaeducacional
      DB_USER: postgres
      DB_PASSWORD: Eunaoseiasenha22
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - plataforma-network

  frontend:
    container_name: plataforma-educacional-frontend-1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - plataforma-network

networks:
  plataforma-network:
    driver: bridge
